#!/bin/sh
# Fills the test mailbox with messages. docs/04 §Phase 5 exit gate — "a 50k-message mailbox".
#
#   ./seed.sh 50000
#
# Written straight into the Maildir rather than APPENDed over IMAP. Fifty thousand APPENDs is
# an hour of round trips and measures the *server's* throughput, which is not what the gate is
# about; the gate is about Halcyon syncing a mailbox that is already large.
#
# Generated by awk rather than a shell loop. The shell version forked `date` once per message
# and would have taken the better part of an hour for fifty thousand; awk does the whole thing
# in one process.
#
# The messages are deliberately varied. Fifty thousand identical ones would prove nothing about
# threading, parsing or the list: there are threads with real `References` chains, a spread of
# dates so keyset pagination is exercised over a real range, HTML with quoted replies and
# tracking numbers, a proportion already marked read, and some with the malformed headers and
# missing charsets that real mail is full of.
set -eu

COUNT="${1:-50000}"
CONTAINER="${CONTAINER:-halcyon-dovecot}"
USER_MAIL="tester@halcyon.test"

echo "seeding $COUNT messages into $USER_MAIL ..."

docker exec -i "$CONTAINER" sh -s "$COUNT" "$USER_MAIL" <<'INNER'
set -eu
COUNT="$1"
USER_MAIL="$2"
BASE="/srv/mail/$USER_MAIL/Maildir"
mkdir -p "$BASE/new" "$BASE/cur" "$BASE/tmp"

awk -v count="$COUNT" -v base="$BASE" -v mailbox="$USER_MAIL" '
BEGIN {
  for (i = 1; i <= count; i++) {
    # Threads of twenty, numbered from 1 so that every thread root actually exists. The first
    # version numbered from 0, which left thread 0 replying to a message that was never
    # generated — a dangling parent is a real case worth testing, but not one to create by
    # accident in every twentieth thread.
    thread   = int((i - 1) / 20)
    root     = thread * 20 + 1
    sender   = i % 97
    # 37 seconds apart, so fifty thousand messages span about three weeks.
    ts       = 1700000000 + i * 37
    date     = strftime("%a, %d %b %Y %H:%M:%S +0000", ts)

    # Nine in ten already read. A mailbox where everything is unread makes the unread counts
    # trivially equal to the totals, and the badge logic would never be exercised.
    if (i % 10 == 0) { dir = "new"; suffix = "" }
    else             { dir = "cur"; suffix = ":2,S" }

    file = base "/" dir "/" ts "." i ".halcyon" suffix

    print "Return-Path: <sender" sender "@example.test>"          > file
    print "Message-ID: <msg-" i "@halcyon.test>"                  > file
    if (i != root) {
      parent = i - 1
      print "In-Reply-To: <msg-" parent "@halcyon.test>"          > file
      # The root twice over would be wrong when the parent *is* the root.
      if (parent == root) {
        print "References: <msg-" root "@halcyon.test>"           > file
      } else {
        print "References: <msg-" root "@halcyon.test> <msg-" parent "@halcyon.test>" > file
      }
      subject = "Re: Thread " thread ": the quarterly figures"
    } else {
      subject = "Thread " thread ": the quarterly figures"
    }
    print "From: Sender " sender " <sender" sender "@example.test>" > file
    print "To: Tester <" mailbox ">"                               > file
    print "Subject: " subject                                     > file
    print "Date: " date                                           > file

    if (i % 11 == 0) {
      # HTML with a quoted reply and a tracking number — what the reader folding and the data
      # detectors are for.
      print "MIME-Version: 1.0"                                   > file
      print "Content-Type: text/html; charset=utf-8"              > file
      print ""                                                    > file
      print "<p>Message " i ". Tracking 1Z999AA1012345678" (i % 10) ".</p>" > file
      print "<blockquote><p>The previous message in thread " thread ".</p></blockquote>" > file
    } else if (i % 17 == 0) {
      # No charset declared. Real mail is full of this and the parser has to cope.
      print "Content-Type: text/plain"                            > file
      print ""                                                    > file
      print "Message " i " with no charset declared."             > file
    } else {
      print "MIME-Version: 1.0"                                   > file
      print "Content-Type: text/plain; charset=utf-8"             > file
      print ""                                                    > file
      print "Message " i " in thread " thread "."                 > file
    }

    # Without this awk runs out of file descriptors within a few hundred messages.
    close(file)

    if (i % 10000 == 0) { printf "  ... %d\n", i > "/dev/stderr" }
  }
}' </dev/null

chown -R 1000:1000 "/srv/mail/$USER_MAIL"
echo "written: $(ls "$BASE/cur" | wc -l) read, $(ls "$BASE/new" | wc -l) unread"
INNER

echo "indexing (this is Dovecot's first read of the mailbox) ..."
docker exec "$CONTAINER" doveadm force-resync -u "$USER_MAIL" INBOX >/dev/null 2>&1 || true
docker exec "$CONTAINER" doveadm mailbox status -u "$USER_MAIL" messages unseen INBOX
